/* ============================================================
   兵工廠人員分配系統 - 多國語言字典與建築設定 (i18n.js)
   ============================================================ */

const langPack = {
  zht: {
    introText: "兵工廠人員分配系統準備中...",
    btnHistoryModal: "📂 編輯歷史分配紀錄",
    btnViewSystem: "📲 進入檢視系統",
    btnOldSystem: "📲 查看舊版本分配系統",
    btnCancelEdit: "取消編輯 (恢復全新發布)",
    mainTitle: "兵工廠人員分配系統 PRO",
    infoTitle: "當前兵工廠建築清單：",
    infoItems: [
      "1號武器試驗場 (6000)",
      "2號武器試驗場 (6000)",
      "1號武器維修站 (3000)",
      "2號武器維修站 (3000)",
      "3號武器維修站 (3000)",
      "4號武器維修站 (3000)",
      "中繼站 (1200)",
      "蒸氣鍋爐 (1700)",
    ],
    leaderTitle: "各組隊長設定 (戰力需 ≥ 4000)",
    labels: [
      "第一組隊長（1號武器試驗場 & 1號武器維修廠）",
      "第二組隊長（2號武器試驗場 & 2號武器維修廠）",
      "第三組隊長（3號武器維修廠 & 中轉站.）",
      "第四組隊長（4號武器維修廠 & 蒸氣鍋爐）",
    ],
    placeholders: {
      name: "輸入或點擊指派隊長名字",
      power: "輸入隊長戰力",
      list: "請在此輸入整隊隊員名單...",
    },
    viceAccordionTitle: "⚙️ 進階設定：手動指定各組副隊長 (預設自動揀選)",
    viceNoticeText:
      "💡 提示：手動指定之副隊長會自動併入平衡分配，無需在主名單重複輸入。",
    viceLabels: [
      "第 1 組副隊長 (維修廠 I)",
      "第 2 組副隊長 (維修廠 II)",
      "第 3 組副隊長 (中轉站)",
      "第 4 組副隊長 (蒸氣鍋爐)",
    ],
    vicePlaceholderName: "副隊長名字",
    vicePlaceholderPower: "副隊長戰力",
    memberTitle: "參戰隊員分配區",
    labelMainList: "⚔️ 1. 主平衡分配名單 (一行為一筆：名字 戰力)",
    memberDesc:
      "填入此區的人員會自動依戰力<strong>平均拆分</strong>進入 8 大建築。",
    labelGatherList: "⚡ 2. 採集小隊名單 (手動填寫)",
    labelAmmoList: "🎒 3. 子彈小隊名單 (手動填寫)",
    gatherPlaceholder: "輸入負責採集的人名，一行為一人 (例：塔卡)",
    ammoPlaceholder: "輸入撿子彈的 8 人名單，一行為一人",
    btnDistribute: "開始戰力平衡分配",
    btnLoadTestData: "載入測試用資料",
    quickTitle: "⚡ 快速指派隊長（點擊填入左側空缺）",
    btnPublish: "☁️ 發布最新分配結果 (公開給所有人檢視)",
    summaryTitle: "📊 數據總計",
    copyTitle: "📋 分配後的人員清單 (可直接複製)",
    btnCopyText: "點擊一鍵複製名單",
    tweakTitle: "⚡ 建築物人員微調區 (可直接滑鼠拖曳名字更換位置)",
    btnScreenshotText: "點擊截圖表格區並儲存",
    summaryText: ["總參戰人數", "總體總戰力", "每大組平均戰力"],
    buildingPower: "目前戰力：",
    leaderTag: "隊長",
    viceTag: "副隊長",
    alertRepeat: "已經被指派為其中一組的隊長囉！",
    alertFull: "目前的 4 個組別皆已有隊長名字，無剩餘空缺。",
    alertSuccess: "分配名單已成功複製到剪貼簿！",
    modalTitle: "🛡️ 戰前名單資料確認",
    modalDesc: "請確認以下輸入的作戰人員數據是否準確：",
    modalCancel: "返回",
    modalConfirm: "確認無誤，開始分配",
    overviewTitle: "[戰力人數總覽]",
    overviewCountText: "去重後預計出征：",
    overviewCountUnit: " 人",
    leaderPreviewTitle: "[四大組隊長預覽]",
    leaderGText: "第 ",
    leaderGUnit: " 組隊長: ",
    mainPoolTitle: "[主平衡分配組 (",
    gatherPoolTitle: "[手動指派：採集小隊 (",
    ammoPoolTitle: "[手動指派：子彈小隊 (",
    poolUnit: " 人)]",
    emptyText: "(空)",
    specLabelGather: "戰場開啟15分鐘後負責幫忙採集",
    specLabelAmmo: "當建築防守失敗時幫忙撿散落子彈",
    specTitleGather: "採集小隊",
    specTitleAmmo: "子彈小隊",
    specPowerLabel: "手動指派支援",
    specPowerLabelAmmo: "手動負責人員",
    changelogTitle: "💾 系統更新紀錄",
    changelogDesc: "本系統之歷史重構與優化明細項目：",
    btnCloseChangelog: "關閉視窗 / Close",
    publishHeader: "☁️ 發布分配結果",
    lblPublishLegion: "1. 請選擇發布軍團 (Legion)：",
    lblPublishEventType: "2. 請選擇活動名稱：",
    lblPublishTitle: "3. 標題 / Title：(自動填入 / Auto fill in)：",
    lblPublishAuthor: "4. 分配員暱稱：",
    lblPublishPasscode: "5. 設定存取密碼 (停用中)：",
    btnPublishCancel: "取消",
    btnConfirmPublish: "確認並發布",
    uiLoadHistoryTitle: "📂 編輯歷史分配紀錄",
    lblLoadHistory: "選擇要載入的分配紀錄：",
    lblLoadLegion: "選擇要載入的軍團：",
    lblLoadPasscode: "解鎖密碼 (若該紀錄受密碼保護需填寫)：",
    btnLoadCancel: "取消",
    btnConfirmLoad: "繼續",
    groupTitles: [
      "第一組 (試驗場 I & 維修廠 I)",
      "第二組 (試驗場 II & 維修廠 II)",
      "第三組 (維修廠 III & 中轉站)",
      "第四組 (維修廠 IV & 蒸氣鍋爐)",
      "特殊支援小隊 (採集 & 子彈)",
    ],
    btnMapScreenshot: "🗺️ 下載「兵工廠地圖版」人員分配圖",
    mapProcessing: "⏳ 正在合成地圖與分配名單...",
    selectLabel: "📜 選擇分配紀錄：",
    metaAuthor: "分配人員：",
    metaTime: "發布時間：",
  },
  en: {
    introText: "Foundry Allocation System Initializing...",
    btnHistoryModal: "📂 Edit History Record",
    btnViewSystem: "📲 Viewer System",
    btnOldSystem: "📲 Old Version",
    btnCancelEdit: "Cancel Edit (Reset)",
    mainTitle: "Foundry Personnel Allocation System PRO",
    infoTitle: "Current Arsenal Buildings:",
    infoItems: [
      "Prototype Site I (6000)",
      "Prototype Site II (6000)",
      "Repair Facility I (3000)",
      "Repair Facility II (3000)",
      "Repair Facility III (3000)",
      "Repair Facility IV (3000)",
      "Transit Station (1200)",
      "Boiler Room (1700)",
    ],
    leaderTitle: "Leader Settings (Power ≥ 4000)",
    labels: [
      "Group 1 (Prototype Site I & Repair Facility I)",
      "Group 2 (Prototype Site II & Repair Facility II)",
      "Group 3 (Repair Facility III & Transit Station)",
      "Group 4 (Repair Facility IV & Boiler Room)",
    ],
    placeholders: {
      name: "Enter or click to assign leader",
      power: "Enter leader power",
      list: "Enter player roster here...",
    },
    viceAccordionTitle: "⚙️ Advanced: Manual Assign Vice-CDR (Optional)",
    viceNoticeText:
      "💡 Note: Manually assigned V-CDRs will be auto-balanced. No need to re-enter in the main list.",
    viceLabels: [
      "Group 1 V-CDR (Repair Facility I)",
      "Group 2 V-CDR (Repair Facility II)",
      "Group 3 V-CDR (Transit Station)",
      "Group 4 V-CDR (Boiler Room)",
    ],
    vicePlaceholderName: "V-CDR Name",
    vicePlaceholderPower: "V-CDR Power",
    memberTitle: "Personnel Dashboard",
    labelMainList:
      "⚔️ 1. Main Balancing Roster (One per line: Name Power)",
    memberDesc:
      "Players in this pool will be automatically balanced into the 8 buildings.",
    labelGatherList: "⚡ 2. Gathering Squad Roster (Manual)",
    labelAmmoList: "🎒 3. Ammo Squad Roster (Manual)",
    gatherPlaceholder:
      "Enter names for gathering, one per line (e.g., Taca)",
    ammoPlaceholder: "Enter up to 8 names for ammo squad, one per line",
    btnDistribute: "Start Balance Allocation",
    btnLoadTestData: "Load Test Data",
    quickTitle: "⚡ Quick Assign Leader (Click to fill empty slot below)",
    btnPublish: "☁️ Publish Result (Public View)",
    summaryTitle: "📊 Summary",
    copyTitle: "📋 Allocation Roster (Ready to copy)",
    btnCopyText: "Click to Copy Roster",
    tweakTitle:
      "⚡ Drag & Drop adjustment zone (Drag name tags to re-allocate)",
    btnScreenshotText: "Capture Dashboard & Save",
    summaryText: [
      "Total Players",
      "Total Power",
      "Average Power / Group",
    ],
    buildingPower: "Power: ",
    leaderTag: "CDR",
    viceTag: "V-CDR",
    alertRepeat: " has already been assigned as a leader!",
    alertFull: "All 4 groups already have leaders assigned.",
    alertSuccess: "Roster copied to clipboard successfully!",
    modalTitle: "🛡️ Pre-match Roster Verification",
    modalDesc: "Please verify that the inputted combat data is correct:",
    modalCancel: "Back to Edit",
    modalConfirm: "Confirm & Allocate",
    overviewTitle: "[Personnel Overview]",
    overviewCountText: "Est. Deployment (Deduplicated): ",
    overviewCountUnit: " players",
    leaderPreviewTitle: "[Group Leaders Preview]",
    leaderGText: "Group ",
    leaderGUnit: " CDR: ",
    mainPoolTitle: "[Main Balanced Pool (",
    gatherPoolTitle: "[Manual: Gathering Squad (",
    ammoPoolTitle: "[Manual: Ammo Squad (",
    poolUnit: " players)]",
    emptyText: "(Empty)",
    specLabelGather:
      "Responsible for gathering 15 mins after match start",
    specLabelAmmo:
      "Responsible for collecting scattered ammo if building falls",
    specTitleGather: "Gathering Squad",
    specTitleAmmo: "Ammo Squad",
    specPowerLabel: "Manual Assigned",
    specPowerLabelAmmo: "Manual Assigned",
    changelogTitle: "💾 System Changelog",
    changelogDesc:
      "History of system restructuring and optimization details:",
    btnCloseChangelog: "Close Window",
    publishHeader: "☁️ Publish Allocation Results",
    lblPublishLegion: "1. Select Legion:",
    lblPublishEventType: "2. Select Event Type:",
    lblPublishTitle: "3. Generated Allocation Title:",
    lblPublishAuthor: "4. PIC / Author Name:",
    lblPublishPasscode: "5. Passcode (Disabled):",
    btnPublishCancel: "Cancel",
    btnConfirmPublish: "Confirm & Publish",
    uiLoadHistoryTitle: "📂 Edit History Record",
    lblLoadHistory: "Select Allocation Record:",
    lblLoadLegion: "Select Legion:",
    lblLoadPasscode: "Unlock Passcode (If protected):",
    btnLoadCancel: "Cancel",
    btnConfirmLoad: "Continue",
    groupTitles: [
      "Group 1 (Site I & Repair I)",
      "Group 2 (Site II & Repair II)",
      "Group 3 (Repair III & Transit)",
      "Group 4 (Repair IV & Boiler)",
      "Special Squads (Gathering & Ammo)",
    ],
    btnMapScreenshot: "🗺️ Download map version allocation results",
    mapProcessing: "⏳ Generating...",
    selectLabel: "📜 Select Allocation Record: ",
    metaAuthor: "PIC: ",
    metaTime: "Published Time: ",
  },
};

const buildingsConfig = [
  {
    id: "b0",
    nameZht: "1號武器試驗場",
    nameEn: "Prototype Site I",
    gIdx: 0,
    needVice: false,
  },
  {
    id: "b1",
    nameZht: "1號武器維修廠",
    nameEn: "Repair Facility I",
    gIdx: 0,
    needVice: true,
  },
  {
    id: "b2",
    nameZht: "2號武器試驗場",
    nameEn: "Prototype Site II",
    gIdx: 1,
    needVice: false,
  },
  {
    id: "b3",
    nameZht: "2號武器維修廠",
    nameEn: "Repair Facility II",
    gIdx: 1,
    needVice: true,
  },
  {
    id: "b4",
    nameZht: "3號武器維修廠",
    nameEn: "Repair Facility III",
    gIdx: 2,
    needVice: false,
  },
  {
    id: "b5",
    nameZht: "中轉站.",
    nameEn: "Transit Station",
    gIdx: 2,
    needVice: true,
  },
  {
    id: "b6",
    nameZht: "4號武器維修廠",
    nameEn: "Repair Facility IV",
    gIdx: 3,
    needVice: false,
  },
  {
    id: "b7",
    nameZht: "蒸氣鍋爐",
    nameEn: "Boiler Room",
    gIdx: 3,
    needVice: true,
  },
];